2025-10-14 23:32:13.320 Port 8501 is already in use
2025-10-14 23:32:24.034 Port 8501 is already in use
2025-10-14 23:32:34.612 Port 8501 is already in use
2025-10-14 23:32:45.226 Port 8501 is already in use
2025-10-14 23:32:55.723 Port 8501 is already in use
2025-10-14 23:33:06.231 Port 8501 is already in use
2025-10-14 23:33:16.740 Port 8501 is already in use
2025-10-14 23:33:27.230 Port 8501 is already in use
2025-10-14 23:33:37.735 Port 8501 is already in use
2025-10-14 23:33:48.229 Port 8501 is already in use
2025-10-14 23:33:58.727 Port 8501 is already in use
2025-10-14 23:34:09.243 Port 8501 is already in use
2025-10-14 23:34:19.736 Port 8501 is already in use
2025-10-14 23:34:30.230 Port 8501 is already in use
2025-10-14 23:50:44.297 Uncaught app execution
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 593, in code_to_exec
    exec(code, module.__dict__)
  File "/data/xuanrenSong/CM_Power_Website/app.py", line 8, in <module>
    from streamlit_toggle import st_toggle_switch
ModuleNotFoundError: No module named 'streamlit_toggle'
2025-10-14 23:52:25.751 Uncaught app execution
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 593, in code_to_exec
    exec(code, module.__dict__)
  File "/data/xuanrenSong/CM_Power_Website/app.py", line 8, in <module>
    from streamlit_toggle import st_toggle_switch
ModuleNotFoundError: No module named 'streamlit_toggle'
Task exception was never retrieved
future: <Task finished name='Task-11093' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /opt/miniconda3/lib/python3.12/site-packages/tornado/websocket.py:1086> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/tornado/websocket.py", line 1088, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/tornado/websocket.py", line 1090, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-11094' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /opt/miniconda3/lib/python3.12/site-packages/tornado/websocket.py:1086> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/tornado/websocket.py", line 1088, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/tornado/websocket.py", line 1090, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-11095' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /opt/miniconda3/lib/python3.12/site-packages/tornado/websocket.py:1086> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/tornado/websocket.py", line 1088, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/tornado/websocket.py", line 1090, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
